repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.1.0
   hooks:
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: forbid-new-submodules
    - id: requirements-txt-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: check-added-large-files
      args: ['--maxkb=100']
 - repo: https://github.com/pycqa/isort
   rev: 5.10.1
   hooks:
    - id: isort
      name: isort (python)
    - id: isort
      name: isort (cython)
      types: [cython]
    - id: isort
      name: isort (pyi)
      types: [pyi]
 - repo: https://github.com/asottile/pyupgrade
   rev: v2.31.1
   hooks:
    - id: pyupgrade
      args: [--py39-plus]
 - repo: https://github.com/ambv/black
   rev: 22.3.0
   hooks:
    - id: black
      language_version: python3.9
 - repo: https://github.com/asottile/blacken-docs
   rev: v1.12.1
   hooks:
    - id: blacken-docs
      additional_dependencies: [black==22.3.0]
