[workflow]
name = {type="str", default="wgs"}

[sample]
runid = {type="str"}
input_dir = {type="path", default="{params.input_dir}/{.runid}", required=true}

[params]
input_dir = {type="path", required=true}
output_dir = {type="path", required=true}

[input]
input_dir = {type="path", default="{params.input_dir}", required=true}

[output]
output_dir = {type="path", default="{params.output_dir}", required=true}
summary = {type="path", default="{.output_dir}/wgs_summary.json", required=true}

[scratch]
output_dir = {type="path"}

[merge_bias_cv.options]
bias_cv_threshold = {type="float", default=0.2}
include_chromosome = {type="str", default="^chr([2][0-2]$|[1][0-9]$|[1-9]$)"}

[readcounter.options]
quality = {type="int", default=20}
chromosome = {type="str", default="chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY"}

[get_wgs_cov_bias.options]
norm_samples = {type="list[str]", default=[
    "GM12878-100c-Res-KAPA_S3" ,
    "GM12878-200c-Res-KAPA_S4",
    "GM24143-100c-Res-KAPA_S7",
    "GM24143-200c-Res-KAPA_S8",
    "GM24143-50c-Res-KAPA_S6",
    "GM24149-100c-Res-KAPA_S11",
    "GM24149-200c-Res-KAPA_S12",
    "GM24149-50c-Res-KAPA_S10",
    "GM24385-100c-Res-KAPA_S15",
    "GM24385-200c-Res-KAPA_S16",
    "GM24385-50c-Res-KAPA_S14",
    "HFL1-100c-Res-KAPA_S23",
    "HFL1-200c-Res-KAPA_S24",
    "HFL1-50c-Res-KAPA_S22",
]}

[parse_bam.options]
min_mapq = {type="int", default=50}
# FIXME: limited choices for bsize once verification / validation done to identify reasonable values
alignment_bsize = {type="int", default=1000000}
gc_bsize = {type="int", default=1000}

[ichorcna.options]
ploidy = {type="str", default="c(1.75,2,2.25)"}
normal_fraction = {type="str", default="c(0.01,0.1,0.25,0.5,0.75,0.9,0.99)"}
chrs = {type="str", default="c(1:22,\"X\")"}
chr_train = {type="str", default="c(1:22)"}
txne = {type="float", default=0.9999}
txn_strength = {type="int", default=10000}

[ichorcna.flags]
include_homd = {type="bool", default=false}
estimate_normal = {type="bool", default=true}
estimate_ploidy = {type="bool", default=true}
estimate_scprevalence = {type="bool", default=false}
